import Foundation
import Yams

struct RuntimeConfigBuilder {
    private typealias YAMLMap = [String: Any]

    private let managedKeys: Set<String> = [
        "mixed-port",
        "socks-port",
        "allow-lan",
        "mode",
        "log-level",
        "external-controller",
        "external-ui",
        "external-ui-name",
        "external-ui-url",
        "secret",
        "dns",
        "sniffer",
        "tun"
    ]

    func build(
        profileContent: String,
        settings: AppSettings,
        fragments: [ConfigFragment] = [],
        disabledRules: Set<String> = []
    ) throws -> String {
        var userMap = try yamlMapping(from: profileContent, label: "profile")
        removeManagedKeys(from: &userMap)

        if settings.yamlOverrideEnabled {
            for fragment in fragments where fragment.enabled && fragment.kind == .yaml {
                let fragmentMap = try yamlMapping(from: fragment.content, label: fragment.name)
                userMap = deepMerge(userMap, fragmentMap)
            }
        }

        removeManagedKeys(from: &userMap)
        filterDisabledRules(in: &userMap, disabledRules: disabledRules)

        var finalMap = generatedOverlay(settings: settings)
        for (key, value) in userMap {
            finalMap[key] = value
        }

        let dumped = try Yams.dump(object: finalMap, sortKeys: false)
            .trimmingCharacters(in: .whitespacesAndNewlines)
        return "# Generated by Mihomo. Managed keys are merged through the YAML parser.\n\(dumped)\n"
    }

    private func generatedOverlay(settings: AppSettings) -> YAMLMap {
        var overlay: YAMLMap = [
            "mixed-port": settings.mixedPort,
            "allow-lan": settings.allowLAN,
            "mode": "rule",
            "log-level": settings.logLevel,
            "external-controller": "\(controllerBindHost(settings)):\(settings.controllerPort)"
        ]

        if settings.socksPort > 0 {
            overlay["socks-port"] = settings.socksPort
        }

        if settings.controllerSecret.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty == false {
            overlay["secret"] = settings.controllerSecret
        }

        if settings.externalUIEnabled {
            let uiPath = AppPaths.externalUIDirectory
                .appendingPathComponent(settings.externalUIName, isDirectory: true)
                .path
            overlay["external-ui"] = uiPath
            overlay["external-ui-name"] = settings.externalUIName
            if settings.externalUIDownloadURL.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty == false {
                overlay["external-ui-url"] = settings.externalUIDownloadURL
            }
        }

        if settings.dnsNameservers.isEmpty == false || settings.dnsFallbacks.isEmpty == false {
            overlay["dns"] = dnsMap(settings)
        }

        if settings.snifferEnabled {
            overlay["sniffer"] = snifferMap(settings)
        }

        if settings.tunEnabled {
            overlay["tun"] = [
                "enable": true,
                "stack": "system",
                "auto-route": true,
                "auto-detect-interface": true,
                "dns-hijack": ["any:53"]
            ]
        }

        return overlay
    }

    private func controllerBindHost(_ settings: AppSettings) -> String {
        settings.remoteAPIEnabled ? settings.remoteAPIBindAddress : "127.0.0.1"
    }

    private func snifferMap(_ settings: AppSettings) -> YAMLMap {
        let ports: [Any] = lineList(settings.snifferPorts).map { value in
            if let port = Int(value) {
                return port
            }
            return value
        }
        let effectivePorts: [Any] = ports.isEmpty ? [80, 443] : ports
        var map: YAMLMap = [
            "enable": true,
            "sniff": [
                "HTTP": ["ports": effectivePorts],
                "TLS": ["ports": effectivePorts]
            ]
        ]

        let forceDomains = lineList(settings.snifferForceDomains)
        let skipDomains = lineList(settings.snifferSkipDomains)
        if forceDomains.isEmpty == false {
            map["force-domain"] = forceDomains
        }
        if skipDomains.isEmpty == false {
            map["skip-domain"] = skipDomains
        }
        return map
    }

    private func dnsMap(_ settings: AppSettings) -> YAMLMap {
        var map: YAMLMap = [
            "enable": true,
            "enhanced-mode": settings.dnsEnhancedMode,
            "nameserver": settings.dnsNameservers.isEmpty ? ["system"] : settings.dnsNameservers
        ]
        if settings.dnsFallbacks.isEmpty == false {
            map["fallback"] = settings.dnsFallbacks
        }
        return map
    }

    private func filterDisabledRules(in map: inout YAMLMap, disabledRules: Set<String>) {
        guard disabledRules.isEmpty == false,
              let rules = map["rules"] as? [Any]
        else { return }

        map["rules"] = rules.filter { item in
            guard let rule = item as? String else { return true }
            return disabledRules.contains(rule.trimmingCharacters(in: .whitespacesAndNewlines)) == false
        }
    }

    private func lineList(_ text: String) -> [String] {
        text.components(separatedBy: CharacterSet(charactersIn: ",\n"))
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
    }

    private func removeManagedKeys(from map: inout YAMLMap) {
        for key in managedKeys {
            map.removeValue(forKey: key)
        }
    }

    private func deepMerge(_ base: YAMLMap, _ overlay: YAMLMap) -> YAMLMap {
        var result = base
        for (key, value) in overlay {
            if let current = result[key] as? YAMLMap,
               let next = value as? YAMLMap {
                result[key] = deepMerge(current, next)
            } else {
                result[key] = value
            }
        }
        return result
    }

    private func yamlMapping(from content: String, label: String) throws -> YAMLMap {
        let trimmed = content.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.isEmpty == false else { return [:] }
        let object = try Yams.load(yaml: content) ?? [:]
        guard let map = normalizeYAMLValue(object) as? YAMLMap else {
            throw NSError(domain: "RuntimeConfigBuilder", code: 1, userInfo: [
                NSLocalizedDescriptionKey: "\(label) 必须是 YAML 顶层映射。"
            ])
        }
        return map
    }

    private func normalizeYAMLValue(_ value: Any) -> Any {
        if let map = value as? YAMLMap {
            return map.reduce(into: YAMLMap()) { result, pair in
                result[pair.key] = normalizeYAMLValue(pair.value)
            }
        }
        if let map = value as? [AnyHashable: Any] {
            return map.reduce(into: YAMLMap()) { result, pair in
                result[String(describing: pair.key)] = normalizeYAMLValue(pair.value)
            }
        }
        if let array = value as? [Any] {
            return array.map { normalizeYAMLValue($0) }
        }
        return value
    }
}
