import Foundation
import Yams

struct RuntimeConfigBuilder {
    private typealias YAMLMap = [String: Any]

    func build(
        profileContent: String,
        settings: AppSettings,
        fragments: [ConfigFragment] = [],
        disabledRules: Set<String> = []
    ) throws -> String {
        var configuredMap = try yamlMapping(from: profileContent, label: "profile")

        if settings.yamlOverrideEnabled {
            for fragment in fragments where fragment.enabled && fragment.kind == .yaml {
                let fragmentMap = try yamlMapping(from: fragment.content, label: fragment.name)
                configuredMap = deepMerge(configuredMap, fragmentMap)
            }
        }

        filterDisabledRules(in: &configuredMap, disabledRules: disabledRules)

        var finalMap = deepMerge(generatedOverlay(settings: settings), configuredMap)
        enforceAppManagedControlChannel(in: &finalMap, settings: settings)
        enforceAppManagedSniffer(in: &finalMap, settings: settings)

        let dumped = try Yams.dump(object: finalMap, sortKeys: false)
            .trimmingCharacters(in: .whitespacesAndNewlines)
        return "# Generated by Mihomo. App settings provide defaults; Profile and enabled overrides take priority.\n\(dumped)\n"
    }

    private func generatedOverlay(settings: AppSettings) -> YAMLMap {
        var overlay: YAMLMap = [
            "mixed-port": settings.mixedPort,
            "allow-lan": settings.allowLAN,
            "mode": "rule",
            "log-level": settings.logLevel,
            "external-controller": "\(controllerBindHost(settings)):\(settings.controllerPort)"
        ]

        if settings.socksPort > 0 {
            overlay["socks-port"] = settings.socksPort
        }

        if settings.controllerSecret.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty == false {
            overlay["secret"] = settings.controllerSecret
        }

        if settings.externalUIEnabled {
            let uiPath = AppPaths.externalUIDirectory
                .appendingPathComponent(settings.externalUIName, isDirectory: true)
                .path
            overlay["external-ui"] = uiPath
            overlay["external-ui-name"] = settings.externalUIName
            if settings.externalUIDownloadURL.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty == false {
                overlay["external-ui-url"] = settings.externalUIDownloadURL
            }
        }

        if settings.dnsNameservers.isEmpty == false || settings.dnsFallbacks.isEmpty == false {
            overlay["dns"] = dnsMap(settings)
        }

        if settings.snifferManagedByApp && settings.snifferEnabled {
            overlay["sniffer"] = snifferMap(settings)
        }

        if settings.tunEnabled {
            overlay["tun"] = [
                "enable": true,
                "stack": "system",
                "auto-route": true,
                "auto-detect-interface": true,
                "dns-hijack": ["any:53"]
            ]
        }

        return overlay
    }

    private func controllerBindHost(_ settings: AppSettings) -> String {
        settings.remoteAPIEnabled ? settings.remoteAPIBindAddress : "127.0.0.1"
    }

    private func snifferMap(_ settings: AppSettings) -> YAMLMap {
        let httpPorts = portList(settings.snifferHTTPPorts, fallback: [80, 443])
        let tlsPorts = portList(settings.snifferTLSPorts, fallback: [443])
        let quicPorts = portList(settings.snifferQUICPorts, fallback: [])
        var sniff: YAMLMap = [
            "HTTP": [
                "ports": httpPorts,
                "override-destination": settings.snifferOverrideDestination
            ],
            "TLS": ["ports": tlsPorts]
        ]
        if quicPorts.isEmpty == false {
            sniff["QUIC"] = ["ports": quicPorts]
        }

        var map: YAMLMap = [
            "enable": true,
            "parse-pure-ip": settings.snifferParsePureIP,
            "force-dns-mapping": settings.snifferForceDNSMapping,
            "override-destination": settings.snifferOverrideDestination,
            "sniff": sniff
        ]

        let forceDomains = lineList(settings.snifferForceDomains)
        let skipDomains = lineList(settings.snifferSkipDomains)
        let skipDestinationAddresses = lineList(settings.snifferSkipDestinationAddresses)
        let skipSourceAddresses = lineList(settings.snifferSkipSourceAddresses)
        if forceDomains.isEmpty == false {
            map["force-domain"] = forceDomains
        }
        if skipDomains.isEmpty == false {
            map["skip-domain"] = skipDomains
        }
        if skipDestinationAddresses.isEmpty == false {
            map["skip-dst-address"] = skipDestinationAddresses
        }
        if skipSourceAddresses.isEmpty == false {
            map["skip-src-address"] = skipSourceAddresses
        }
        return map
    }

    private func enforceAppManagedControlChannel(in map: inout YAMLMap, settings: AppSettings) {
        map["external-controller"] = "\(controllerBindHost(settings)):\(settings.controllerPort)"
        map.removeValue(forKey: "external-controller-unix")
        map.removeValue(forKey: "external-controller-pipe")

        let secret = settings.controllerSecret.trimmingCharacters(in: .whitespacesAndNewlines)
        if secret.isEmpty {
            map.removeValue(forKey: "secret")
        } else {
            map["secret"] = secret
        }
    }

    private func enforceAppManagedSniffer(in map: inout YAMLMap, settings: AppSettings) {
        guard settings.snifferManagedByApp else { return }
        if settings.snifferEnabled {
            map["sniffer"] = snifferMap(settings)
        } else {
            map.removeValue(forKey: "sniffer")
        }
    }

    private func portList(_ text: String, fallback: [Int]) -> [Any] {
        let values: [Any] = lineList(text).map { value in
            Int(value).map { $0 as Any } ?? value
        }
        return values.isEmpty ? fallback.map { $0 as Any } : values
    }

    private func dnsMap(_ settings: AppSettings) -> YAMLMap {
        var map: YAMLMap = [
            "enable": true,
            "enhanced-mode": settings.dnsEnhancedMode,
            "nameserver": settings.dnsNameservers.isEmpty ? ["system"] : settings.dnsNameservers
        ]
        if settings.dnsFallbacks.isEmpty == false {
            map["fallback"] = settings.dnsFallbacks
        }
        return map
    }

    private func filterDisabledRules(in map: inout YAMLMap, disabledRules: Set<String>) {
        guard disabledRules.isEmpty == false,
              let rules = map["rules"] as? [Any]
        else { return }

        map["rules"] = rules.filter { item in
            guard let rule = item as? String else { return true }
            return disabledRules.contains(rule.trimmingCharacters(in: .whitespacesAndNewlines)) == false
        }
    }

    private func lineList(_ text: String) -> [String] {
        text.components(separatedBy: CharacterSet(charactersIn: ",\n"))
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
    }

    private func deepMerge(_ base: YAMLMap, _ overlay: YAMLMap) -> YAMLMap {
        var result = base
        for (key, value) in overlay {
            if let current = result[key] as? YAMLMap,
               let next = value as? YAMLMap {
                result[key] = deepMerge(current, next)
            } else {
                result[key] = value
            }
        }
        return result
    }

    private func yamlMapping(from content: String, label: String) throws -> YAMLMap {
        let trimmed = content.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.isEmpty == false else { return [:] }
        let object = try Yams.load(yaml: content) ?? [:]
        guard let map = normalizeYAMLValue(object) as? YAMLMap else {
            throw NSError(domain: "RuntimeConfigBuilder", code: 1, userInfo: [
                NSLocalizedDescriptionKey: "\(label) 必须是 YAML 顶层映射。"
            ])
        }
        return map
    }

    private func normalizeYAMLValue(_ value: Any) -> Any {
        if let map = value as? YAMLMap {
            return map.reduce(into: YAMLMap()) { result, pair in
                result[pair.key] = normalizeYAMLValue(pair.value)
            }
        }
        if let map = value as? [AnyHashable: Any] {
            return map.reduce(into: YAMLMap()) { result, pair in
                result[String(describing: pair.key)] = normalizeYAMLValue(pair.value)
            }
        }
        if let array = value as? [Any] {
            return array.map { normalizeYAMLValue($0) }
        }
        return value
    }
}
